spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://${HOST}/${POSTGRES_DB}?currentSchema=${POSTGRES_SCHEMA}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true
    liquibase-schema: ${POSTGRES_SCHEMA}
    default-schema: ${POSTGRES_SCHEMA}
server:
  port: 8082

topics: ${KAFKA_SUBSCRIBED_TOPICS}